version: 1.0.{build}

branches:
  only:
    - master

environment:
  nodejs_version: "7"

install:
  - npm install

platform:
  - x86
  - x64

test_script:
  - npm test

build_script:
  - npm run dist
